FROM python:3.11

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Start Celery worker
CMD ["celery", "-A", "api.celery_config", "worker", "--loglevel=info"]
