version: "3.8"

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
      celery:
        condition: service_started
    environment:
      - DEBUG=1
      - REDIS_URL=redis://redis:6379/0
      - REDIS_HOST=redis
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/app

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: celery_worker
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: ["celery", "-A", "api.celery_config", "worker", "--loglevel=info"]

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: celery_beat
    depends_on:
      - redis
      - celery
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: ["celery", "-A", "api.celery_config", "beat", "--loglevel=info"]
